
server:
  port: 9096

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cogdbxxa?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: mynewpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  mvc:
  #    converters:
  #      preferred-json-mapper: gson

  # JPA CONFIGURATIONS
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC

    open-in-view: false