server:
  port: 9191


spring:
  application:
    # Application Name
    name: OAUTH2-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
  # DATABASE CONFIGURATIONS
  datasource:
    url: jdbc:mysql://localhost:3306/cogdb1?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: mynewpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  # JPA CONFIGURATIONS
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC

# Spring Boot Admin
  boot:
    admin:
      client:
        url: [http://localhost:4000]
        username: chamath
        password: 1234

logging:
  file:
    name: OAUTH-SERVICE.log
    max-history: 5
    max-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include:  "*"

  endpoint:
    health:
      show-details: always
# --------End Spring Admin------------